### ISSUE TITLE
Faster way to convert videos

### ISSUE THREAD

**Issue by roaldarbol** [raspberrypi-guide/raspberrypi-guide.github.io#2]
Hi Jolle, first off this website is brilliant! Thanks so much for taking the time to compile all this, it is immensely useful! I'm thinking using the issues here is the best way to bring up suggestions for additional parts? I can also make pull requests if you'd be open to "outsider" contributions?
Currently, I could just think of one specific thing which works better, namely a different way of converting videos. 
The current implementation uses `ffmpeg`, which re-encodes the entire video - that takes time, especially if (like me) you work on hour-long videos. However, it's actually not necessary to re-encode the video, it just needs a container (e.g. `.mp4`). This can be done with the `gpac` function `mp4box`, in a fraction of the time. 

#### Installation
```
sudo apt-get update
sudo apt-get install gpac
```

#### Usage
```
mp4box -add filename.h264 filename.mp4
``` 

I haven't explored `gpac` much more, but it has quite a few additional containers and functionalities [worth exploring](https://github.com/gpac/gpac). That being said, it's of course not a substitute for `ffmpeg`, so it's definitely worth keeping both solutions in mind.

**Comment by JolleJolles** [comment]
Hi Roald, thanks for your comment. 

I use FFMpeg as it has much broader functionality than mp4box and actually the implementation I suggest at [https://raspberrypi-guide.github.io/other/convert-h264-ffmpeg](https://raspberrypi-guide.github.io/other/convert-h264-ffmpeg) `ffmpeg -i USER_VIDEO.h264 -vcodec copy USER_VIDEO.mp4` does not re-encode the video just changes the container just like your mp4 command.

But yeah MP4Box provides a simple, fast solution as well so I modified the article on converting to also include a short description about MP4Box (commit [c17c283 ](https://github.com/raspberrypi-guide/raspberrypi-guide.github.io/commit/4287623fe3ce800cd6a055ae6cbb2c575664b2c2)). Thanks for the suggestion!
