### ISSUE TITLE
Currently no support for picamera on Bullseye

### ISSUE THREAD

**Issue by roaldarbol** [raspberrypi-guide/raspberrypi-guide.github.io#4]
Just a heads-up. Raspi have released a new version of their OS, Bullseye. One notable difference is their change from `raspi-cam` to `libcamera`. And accordingly, `picamera` no longer works (see https://github.com/waveform80/picamera/issues/697). However, there's also [no python-bindings for `libcamera` yet](https://www.raspberrypi.com/documentation/accessories/camera.html#python-bindings-for-libcamera), so the suggested action is to stay with Raspi OS Buster. The Buster image is not present in the Raspi Imager, so has to be downloaded elsewhere and can be a bit tricky to find. I found it [here](https://downloads.raspberrypi.org/) under `raspios` where there's both an arm64 and armhf version.

**Comment by JolleJolles** [comment]
Hi Roald, thanks for the message. Yes I was aware of this and left most of my Raspberry Pi's at Buster. I have now updated some pages on the guide to clarify this (commit: e8e9b78e78eadb8527af94038d499ff67a6ebb70). Thanks for sharing the link to the image files too!
